### ISSUE TITLE
Add icons to the social media links in the footer

### ISSUE THREAD

**Issue by palash25** [p-society/p-society.github.io#1]
Maybe we can try icons by font awesome.

This is a beginner friendly issue. Let a first year take this up. @knrt10

**Comment by knrt10** [comment]
Please comment below "I would like to solve this" before working on an issue.

**Comment by palash25** [comment]
Come to think of it we need organization-wide contributing guidelines

**Comment by PBeier** [comment]
I would like to work on this

**Comment by knrt10** [comment]
Feel free to do so. We would really appreciate your contributon @PBeier

**Comment by palash25** [comment]
@PBeier if you are having some trouble implementing this then please ping @knrt10 
He will help you out.

**Comment by debck** [comment]
If there's no update can I work on this?

**Comment by palash25** [comment]
Yes please @debck you can start working on this :+1:
