### ISSUE TITLE
Add Slack invite page

### ISSUE THREAD

**Issue by geekysrm** [p-society/p-society.github.io#11]
Currently, the slack link in footer of PSOC site goes to the link where only registered users can login.. Not valuable for visitors.

Add generate invite page for slack workspace (see example:  https://slackin.now.sh/)

**Comment by shibasisp** [comment]
It's already there. 
Link: http://iiit-bhcoding.herokuapp.com/
token: IIITBBSR

**Comment by knrt10** [comment]
yeah its cool. There were some misconceptions. Will close this issue.

**Comment by palash25** [comment]
Closing it since there is no need for it
