### ISSUE TITLE
Create a page for Achievements by the PSoc Members

### ISSUE THREAD

**Issue by arijeetsat** [p-society/p-society.github.io#13]
A page mentioning all the recent achievements by students in GSoc, Code-Jam, ACM ICPC, Research Institute etc.

**Comment by knrt10** [comment]
Cool

**Comment by palash25** [comment]
Lets list all the achievements 
6 GSoCers
@bkhanale selected for CodeJam  Round 3
@arijeetsat selected for IDBRT internship
P-soc becomes a Mozilla Campus Club

what else what am I missing
@knrt10 and @palash25 install IPFS successfully :laughing:

**Comment by knrt10** [comment]
If you want it like this then will create it.

**Comment by palash25** [comment]
That is needed. Think of it as a `News and Achievements` page where all the individual and group achievements are mentioned in their chronological order

**Comment by knrt10** [comment]
cool

**Comment by gupta2140** [comment]
> what else what am I missing

Season of KDE.

**Comment by arijeetsat** [comment]
Yes , ofcourse add each and every achievements.
Moreover, have to make an Alumni Page as well, opening an issue for it. 👍

**Comment by arijeetsat** [comment]
Actually The main reason of creating an Achievement page is to mention all the technical achievements in college , not only individual ones, but more like the SIH, PlutoAR, Foreign and Indian Internships, Research Publications, Competitive and Kaggle Platform, Selection for Top conferences. It should also go on like an update thing.

**Comment by palash25** [comment]
> final Tech. Website of the college.

Whats that?

> but more like the SIH, PlutoAR,

Thats what I had in mind thats why I suggested to include the previous batches too.

**Comment by shibasisp** [comment]
Something like this we need to build: https://kossiitkgp.in/index.html

**Comment by palash25** [comment]
I think we should mention all the achievements from the start. Dating back to the alumni's time, not just this year's that way we can show how much we have grown individually and as a community

What does everyone think about that?  @p-society/2019-batch @p-society/2020-batch 

If everyone agrees then I will compile a list of all the achievements then post it here so that it can be modified and more things can be added to it.

**Comment by sr6033** [comment]
Go ahead.

**Comment by arijeetsat** [comment]
Yup Good idea .

**Comment by palash25** [comment]
## 2018
- Programming Society becomes an official Mozilla Campus Club.
- Programming Society's first project typeracer-cli surpasses 100 stars on Github.
- Bhushan Khanale makes it into Round 3 of Google Code Jam.
- Abhijeet Panda selected as a Google Summer of Code Student under PSF
- Anish Sarangi selected as a Google Summer of Code Student under Internet Archive
- Ayush Shridhar selected as a Google Summer of Code Student under Julia (NUMFocus)
- Manas Mohapatra selected as a Google Summer of Code Student under Metasploit
- Aman Kumar Gupta selected as a Google Summer of Code Student under KDE
- Palash Nigam selected as a Google Summer of Code Student under coala
- Shibasis Patel selected as a GSOC mentor under Drupal
- Aman Kumar Gupta selected as a Season of KDE student.
- Swapnil Sourabh and Abhishek Patel selected as Research Interns at National University of Singapore
## 2017
- Team PlutoAR wins UnitedByHCL Hackathon in London (team comprised of Ankit Panda, Shourya Pratap Singh and Shushobhit Panigrahi)
-  Shibasis Patel selected as a Google Summer of Code Student under Open Astronomy
- Dibyajyoti Panda  selected as a Google Summer of Code Student under Drupal
- Dibyajyoti Panda  selected as a Google CodeIn Mentor under Drupal
- Shubham Rath, Aman Kumar Gupta & Shivank Tripathi selected for ACM ICPC Kolkata Regionals
- **<can someone fill in the details of the other ICPC team that went to Amritapuri>** @nawedx 
- Team PiedPiper **(someone please fill in the names of the members)** win the Smart India Hackathon.
- **There was another team that made it into the finals of smart india. Can someone fill in their names I think Yash Sinha and Pranshu Malviya were one of the 2 members** 
- **Another team were the finalist in GE Healthhack can someone fill in their names please**  (cc @sr6033 @shibasisp )
- Shivank Pathak becomes the 4th runner up in Kronothon.
- Aman Kumar Gupta secures National Rank 35 in TechGig Code Gladiators
- Shivank Pathak and Abhishek Patel selected as finalist in GDG BBSR Devfest Hackathon
- **There was another team in the GDG finals was it yours** @hdidwania ?
## 2016
- Anirudh Bose selected as a Google Summer of Code Student under Ceph
- Asish Panda selected as a Google Summer of Code Student under PSF
- Team bit_bees **(can someone fill in the names of the members please)** qualify for ACM ICPC Kharagpur regionals
## 2015
- Anirudh Bose selected as a CERN Openlab Intern
- Aroonav Mishra selected as a Google Summer of Code Student under KDE
## 2014
- Anirudh Bose selected as a Google Summer of Code Student under CERN
- Asish Panda selected as a Google Summer of Code Student under SunPy (PSF)
- Anirudh Bose selected as a Research Student at HRI Allahabad.
- IIIT-Bh ACM chapter received the Best ACM Student Chapter runners-up award during ACM India Annual Event at IIT Delhi
## 2013
- Anirudh Bose Selected as a Google Summer of Code Student under GNU Project

This was all I could find from stalking people on LinkedIn. If I have missed something (like an ICPC team, a GSoCer or any other SoC, someone with a CodeChef rank in top 100, a hackathon, etc) please edit/add it in the reverse chronological order. @p-society/2019-batch @p-society/2020-batch 

Also once the page is made it would be nice if people could just add their own achievements as PRs in the future.

@knrt10 could you make a simple page with the following details? Nothing fancy just list them in the order that they have been mentioned in. And it's not urgent so no need to jump on it right now, but I was hoping to get it done a few days before we have our first interaction with the next batch in August.

I hope this is a good start and will be enough to let the juniors know how much we have progressed individually and as a community and will motivate them to make this list even longer.

**Comment by palash25** [comment]
I wasn't expecting the list to be this long. We have progressed a lot.

**Comment by knrt10** [comment]
will add i.

**Comment by AbhiRepository** [comment]
This year Sourabh Kumar, got MITacs scholarship.

**Comment by gupta2140** [comment]
> CodeChef rank in top 100

I remember @bkhanale got a World Rank around 30 in a CodeChef contest sometime ago. Can you please add it?

**Comment by arijeetsat** [comment]
Just a rough draft. Please do edit this:
2018:
-Saurabh Kumar selected for Mitacs Global Scholarship.
-Salona Das and Prashant got an internship in Singapore( @p-society/2019-batch , someone edit this.)
-We should also add the GRE people and those selected for the foreign institute, I guess, Rohan Pattnaik, Yash Sinha , Jeshwin Mathai and some more people.
- 10 teams selected for SIH Grand Finale 2018.

**Comment by bkhanale** [comment]
>I remember @bkhanale got a World Rank around 30 in a CodeChef contest sometime ago.

It was global rank 33 in CodeChef April Long Challenge 2018 Div 1.

**Comment by gupta2140** [comment]
Thanks, I'm adding it to the list.

**Comment by nawedx** [comment]
# 2017
* Avijit Nanda and Sai Saswat Sahu were runner's of GDG BBSR Devfest Hackathon.
* Abhipsha Das and Himansu Didwania selected as finalist in GDG BBSR Devfest Hackathon.

**Comment by shibasisp** [comment]
Here are some of the achievements before 2014 batch we are missing.
http://placement.iiit-bh.ac.in/stud.html

**Comment by palash25** [comment]
@nawedx you made it into the ICPC regionals with Prateek Pattnaik right? Who was the 3rd member?

**Comment by bkhanale** [comment]
>@nawedx you made it into the ICPC regionals with Prateek Pattnaik right? Who was the 3rd member?

It was Bibhu Pala.

**Comment by gupta2140** [comment]
It's already there in the list.

**Comment by arijeetsat** [comment]
> Where in singapore? please add the name of Insititute or Company.

for now just enlisting stuff, will confirm them and add it properly 👍

**Comment by shibasisp** [comment]
It is Singapore University of Technology and Design. But Prashant told me to add this after his project is completed.

**Comment by knrt10** [comment]
@palash25 added. Please check the website

**Comment by knrt10** [comment]
@p-society/2020-batch check the website and for any changes make a PR  [on this folder](https://github.com/p-society/p-society.github.io/tree/master/_trophy)

**Comment by palash25** [comment]
I was in the middle of editing it. @knrt10 nevermid I will make a PR for the rest

**Comment by knrt10** [comment]
sorry for the trouble PP

**Comment by palash25** [comment]
I don't like the colour of the achievements page can you change it to something else.
Maybe gray or green or blue but a lighter shade
