### ISSUE TITLE
Add a carousel to the members section

### ISSUE THREAD

**Issue by palash25** [p-society/p-society.github.io#25]

**Comment by knrt10** [comment]
will do

**Comment by palash25** [comment]
@debck wanna give this a crack?

**Comment by debck** [comment]
Will give a try 😄

**Comment by sudonitesh** [comment]
please give some idea how it should look like. like whether the pictures should be cover size or anything?

**Comment by knrt10** [comment]
Carousel should be for whole cards. Cards should move not images

**Comment by palash25** [comment]
Wait a minute. Lets decide who will be implementing it. I don't want duplicate PRs. @knrt10 @debck @sudonitesh

**Comment by palash25** [comment]
> please give some idea how it should look like. like whether the pictures should be cover size or anything?

I just want the cards to move around so that all the members get a chance to be featured on the homepage.

**Comment by palash25** [comment]
There are other issues that can be split up between the two of you @debck @sudonitesh 
So either you two decide who will be implementing this or we are gonna have to.

**Comment by debck** [comment]
If @sudonitesh wants to try hand with jekyll ,then he can try  as i did one issue already.
I will take some other issue

**Comment by palash25** [comment]
Great @sudonitesh all yours

**Comment by sudonitesh** [comment]
I'm not able to make this responsive when i try to make the carousel with 6 members because with present styling. And any carousel with single member is not looking good with the present style. @debck  please try.

**Comment by palash25** [comment]
You really gonna give up that easy @sudonitesh ? If you give it another try and make it work you might end up learning something. Think about it. If you still don't wanna do it then its fine by me :+1:

**Comment by sudonitesh** [comment]
I made but it's not coming responsive. But still will give another try.

**Comment by palash25** [comment]
Make a WIP PR so that @knrt10 can guide you further and help you make it responsive

**Comment by ntosni** [comment]
ok i will.

**Comment by sudonitesh** [comment]
ok i will. let me try another time

**Comment by palash25** [comment]
@sudonitesh any updates? As a mentioned earlier you can make a WIP (work in progress) PR even if the carousel isn't responsive so that @knrt10 can take a look at your code and guide you through it.

**Comment by palash25** [comment]
And I have sent you a collaborator invite to this repo. Did you accept it?

**Comment by sudonitesh** [comment]
I have not got any confirmation mail. I'll make the PR today.
