### ISSUE TITLE
Create a contact page.

### ISSUE THREAD

**Issue by knrt10** [p-society/p-society.github.io#3]
Its in navbar.

**Comment by geekysrm** [comment]
I would like to work on it @knrt.

**Comment by knrt10** [comment]
Cool

**Comment by knrt10** [comment]
@geekysrm would you please show some progress, due to some time complications this has to be updated soon. Please give a PR in a day otherwise I am sorry you will be unassigned from this.

**Comment by geekysrm** [comment]
Will do. Understanding jekyll.

**Comment by knrt10** [comment]
I thought you knew. I am really sorry if you won’t be able to do it by tomorrow I will have to unassign you cause its time related issue and has to get it up and running for some further cause.

**Comment by geekysrm** [comment]
No worries. Will try to do by tomorrow.

**Comment by knrt10** [comment]
Completed

**Comment by arijeetsat** [comment]
Reopen This issue:

In the contact us page , add links to to the FB pages, Twitter , dribble as well.

**Comment by knrt10** [comment]
Will do, no need to reopen.
