### ISSUE TITLE
Lint the ruby plugin code

### ISSUE THREAD

**Issue by palash25** [p-society/p-society.github.io#36]
What is linting? https://www.wikiwand.com/en/Lint_(software)
Tools helpful in linting:
- https://docs.coala.io/en/latest/Users/Tutorial.html
- https://github.com/rubocop-hq/rubocop

**Comment by palash25** [comment]
If someone wants to try a hand at linting I am fine with giving up this issue. Ping me if you want this and I will remove my assignment.

**Comment by debck** [comment]
@palash25  I would like to work on this issue

**Comment by palash25** [comment]
assigned
