### ISSUE TITLE
Create a blog

### ISSUE THREAD

**Issue by knrt10** [p-society/p-society.github.io#4]
I will be working on it

**Comment by palash25** [comment]
This is the link to our RSS feed. This can be used to build a blog aggregator https://medium.com/feed/programming-society-gazette/

**Comment by palash25** [comment]
@debck wanna try this? It seems a little hard compared to others

**Comment by palash25** [comment]
You will have to build a blog aggregator to get the posts from psoc's medium blog to our site and display them there.

**Comment by palash25** [comment]
Just search *Adding An RSS Feed to a Jekyll Site*

**Comment by debck** [comment]
okay ..at least i can give a try , otherwise i will reply in this thread.
Can u provide any hint on how to approach this stuff.

**Comment by palash25** [comment]
https://github.com/p-society/p-society.github.io/issues/4#issuecomment-403535256

**Comment by palash25** [comment]
@debck coala does this too here is the blog site https://blog.coala.io/ and here is the repo with all the rss links https://github.com/coala/devops/blob/master/venus/planet/planet.ini

I am not sure how they do it and their approach might be too complicated for our use case but still you can look at it for inspiration.

If you want to know how they do it ask on gitter maybe someone will explain it to you (but I'm not sure about it)

**Comment by debck** [comment]
Okay will go through it and ask for more info if needed.
It seems a lot difficult 😄

**Comment by debck** [comment]
Shall i include a new blog page just as the contact page and mention in the nav bar 
like this 
@knrt10 
![image](https://user-images.githubusercontent.com/33368759/42506974-28454816-8461-11e8-970b-c95c5c2ed786.png)

**Comment by knrt10** [comment]
cool

**Comment by debck** [comment]
hey, I am unable to save every post in a `.md` file and even if i try  to implement without saving, just displaying , i am  getting errors on every reload of file .
if someone else wants to take the issue or give some help , it would be good

**Comment by palash25** [comment]
Do we have to save the posts. Can't we just fetch the RSS feed in realtime @knrt10 ?

I have seen blogs do that, they fetch the feed while the site loads I'm not sure why you are saving the posts  @debck ?  Did you look at some jekyll plugins that do this? Like this https://github.com/snaptortoise/jekyll-rss-feeds

**Comment by debck** [comment]
Ya I tried using plugins ..... 
Am not giving up , just need help

**Comment by palash25** [comment]
> Do we have to do this immediately ?

I'm fine if you even take 6 months to do it. There are no time constraints here :wink:

**Comment by knrt10** [comment]
@debck open a PR for what you did.

**Comment by palash25** [comment]
Yeah you can open a WIP PR and then @knrt10 can guide you and you guys can complete it together

**Comment by debck** [comment]
Then it's ok 👍👍...
