### ISSUE TITLE
Add a regex test for member profile link 

### ISSUE THREAD

**Issue by palash25** [p-society/p-society.github.io#62]
the profile.md files of all the members have a field for their profile pictures which is a specific github url. We need to add a Regex test to validate that url so that it runs on every travis build.

@p-society/2021-batch who wants it? If no one claims this issue then @debck will have to do it :stuck_out_tongue_winking_eye:

**Comment by suicide11** [comment]
I would like to try

**Comment by palash25** [comment]
> GitHub profile pic url 

thats the one we want since other pictures might have a different resolution.

**Comment by debck** [comment]
Then some members have to change their URL ( including me)....in order to pass the tests

**Comment by palash25** [comment]
ping @knrt10 need your opinion on this

**Comment by shivank01** [comment]
@palash25 Instead of regex test I would recommend checking the size and resolution of pic so that anyone can upload another pic instead of only github one.

**Comment by palash25** [comment]
I was talking about writing one simple unit test. I have no idea what you are talking about 

> checking the size and resolution of pic 

how do we do this on a static site?

> pic instead of only github one.

github avatars are automatically updated that's why we use them.

Hmmn I got an idea maybe we can use Gravatar. @knrt10 can we do that?
I hope everyone has a gravatar.

**Comment by palash25** [comment]
@suicide11 have you started working on this?  I was thinking about blocking this until we reach a consensus on this.

**Comment by shivank01** [comment]
@palash25 I don't have much idea about web dev. I was saying if it is possible then we should do that.

**Comment by palash25** [comment]
>  I was saying if it is possible then we should do that.

we dont have any backend its a static site so we can't test the images since we are not uploading and storing images to our site but are fetching them from a third party hosting service. Am I right @knrt10 ?

**Comment by sibasish14** [comment]
@palash25 Let's just make this standardised- all members need to upload their GitHub profile pics. So no issues with resolution/size or no need of any tests. What say?

**Comment by palash25** [comment]
That was the initial thought. Lets see what others have to say about that @p-society/2020-batch @p-society/2021-batch 

Opinions here :point_down:

**Comment by debck** [comment]
Only 2-3 members have URL other than github profile. We can change those and then we can write the test. ( I think)

**Comment by palash25** [comment]
Blocked by  #64

I agree with @debck

**Comment by palash25** [comment]
@knrt10 stop making non-sensical labels please.

**Comment by palash25** [comment]
@suicide11 you can get started on this

**Comment by palash25** [comment]
@suicide11 before you start on the PR do you have a clear understanding of the issue and know what changes need to be made?

**Comment by suicide11** [comment]
A test is to be made which will check the picurl (it must be the GitHub profile pic url)

**Comment by palash25** [comment]
> A test is to be made

A test is to be ~~made~~ written.

What I meant was you know how to write tests right?
