### ISSUE TITLE
Change pic url in member profiles

### ISSUE THREAD

**Issue by palash25** [p-society/p-society.github.io#64]
A lot of member profiles don't use github avatars since we want some kind of uniformity lets change all those profile pic urls that don't use github avatars.

Acceptance criterais:
- All such urls are changed.
- PR will contain only one commit.

Who wants it? @p-society/2021-batch

**Comment by debck** [comment]
@Rupeshiya @sudonitesh @pranayag15 anyone wants to try. Or else I will do it

**Comment by pranayag15** [comment]
I'll do it.
