### ISSUE TITLE
Add ACM page

### ISSUE THREAD

**Issue by palash25** [p-society/p-society.github.io#8]

**Comment by knrt10** [comment]
It will be added under events

**Comment by palash25** [comment]
Its not an event

**Comment by knrt10** [comment]
ok.

**Comment by knrt10** [comment]
@palash25 @arijeetsat any ideas about what this page should have?

**Comment by palash25** [comment]
We will do it after the college reopens. Chill and think about backlog in TOC :laughing:

**Comment by palash25** [comment]
closing in favour of #46
