### ISSUE TITLE
:wink logo seems broken (footer section)

### ISSUE THREAD

**Issue by tulsi-prasad** [p-society/p-society.github.io#80]
I was just wandering through the website after attending the Hacktoberfest meetup. It seems the logo in the footer section, having an `alt` text as : wink is broken or needs to be made browser compatible.

**Comment by debck** [comment]
@tulsi-prasad Would you like to make a PR for this?

**Comment by tulsi-prasad** [comment]
Yes, sure. I think we can replace the logo thingy with an Imgur link or a browser compatible emoji, either way, it can work. I'll make a PR by tomorrow afternoon.

**Comment by tulsi-prasad** [comment]
@debck is this #79 issue, needs also to be taken care of? It's just a step away.

**Comment by tulsi-prasad** [comment]
Made a PR #81 after fixing the emoji. Hope this works well.
