### ISSUE TITLE
Add Mozilla campus club page

### ISSUE THREAD

**Issue by palash25** [p-society/p-society.github.io#9]

**Comment by knrt10** [comment]
it will be added under events

**Comment by palash25** [comment]
Not an event

**Comment by knrt10** [comment]
ok

**Comment by palash25** [comment]
@knrt10 can you add something like this *We are also a Mozilla Campus Club. You can find us on their site https://campus.mozilla.community/connect/ * Add it anywhere you please

**Comment by palash25** [comment]
closing in favour of #46
